languages: minimal

git:
  depth: 1

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update -q
  - sudo apt-get install -y emacs26
  - sudo apt-get install -y make default-openjre graphviz

install: skip

script: make

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: ./public
  target_branch: gh-pages
