#+TITLE: Manjaro滚挂了如何回滚
#+KEYWORDS: 珊瑚礁上的程序员, Arch Linux, Manjaro, Pacman
#+DATE: <2024-03-12 Tue>

日常执行 =pacman -Syyuu= 升级系统，不幸的事情发生了，重启之后黑屏了。

具体现象是:
1. 开机后进入 =LUKS= 输入密码页面正常
2. 输入密码后进入 =GRUB= 引导页正常
3. 选择系统后进入登录页面，黑屏了
4. =Ctrl+Alt+F2= 进入 tty 页面无反应（还是黑屏）

** 解决方案

1. 使用 U 盘进入 Manjaro 系统
2. 使用文件管理器访问硬盘，会提示输入 =LUKS= 解密密码（这一步是为了借助文件管理器来解密硬盘并自动挂载，而不用命令行解密和挂载，更便捷）
3. 从文件管理器的地址栏拿到银盘挂载的路径
4. 打开终端，执行 =manjaro-chroot /硬盘挂载路径= 进入系统
5. 查看 pacman 日志文件 =/var/log/pacman.log= ，检查本次升级的软件包有哪些，找出可疑的包（首先怀疑内核升级或 Window Manager）
6. 对可疑的包执行回滚操作（安装升级之前的版本,存在于 pacman 缓存目录） =pacman -U /var/cache/pacman/pkg/linux515-5.15.148-2-x86_64.pkg.tar.zst=
7. 重启查看系统是否恢复正常

我还是比较幸运的，对 linux 内核和 linux 固件回滚到上一个版本后系统就恢复正常了。
#+begin_src shell
  sudo pacman -U /var/cache/pacman/pkg/linux515-5.15.148-2-x86_64.pkg.tar.zst
  sudo pacman -U /var/cache/pacman/pkg/linux-firmware-20240115.9b6d0b08-2-any.pkg.tar.zst
#+end_src
具体是因为这两者中的哪一个，我也不知道。

系统恢复之后再次 =pacman -Syyuu= 升级后依旧还是黑屏，但也不能一直就不升级了吧。
后面尝试升级了内核大版本，从 5.15 升级到 6.10，再执行 =pacman -Syyuu= 升级系统后黑屏现象没有再出现。

** 后记

出现这个问题的时候，刚好着急用电脑，确实慌张的不行，生怕资料也丢了。
处理问题的过程中，甚至一度想着后面换成以稳定著称的 =Debian= 系统了。

生命在于折腾吧~
