name: Build and deploy my blog

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: 28.2

      - name: Start build
        run: make

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          # personal_token: ${{ secrets.ACCESS_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          destination_dir: ./
          force_orphan: true
